Repository gisce/mesures, pull requests merged in 2021-02, with the labels that each got.

#8 Nous fitxers A5D/B5D
  mesures/a5d.py
  mesures/b5d.py
  mesures/headers.py
  mesures/parsers/dummy_data.py
Labels: WIP, enhancement

#7 P2 i P2D
  mesures/f1.py
  mesures/p1.py
  mesures/p1d.py
  mesures/p2.py
  mesures/p2d.py
  mesures/parsers/dummy_data.py
Labels: enhancement

#10 Fix nom de fitxer zip F1 i P1
  mesures/f1.py
  mesures/p1.py
Labels: bug
