Repository gisce/mesures, pull requests merged in 2024-08, with the labels that each got.

#71 Añadir valores por defecto en la creación del fichero REOBJE2
  mesures/reobje2.py
Labels: bug, to be merged :octocat:, distri

#72 Añadir soporte para REOBJECIL
  README.md
  mesures/headers.py
  mesures/reobjecil.py
  spec/generation_files_spec.py
Labels: enhancement, to be merged :octocat:, distri

#74 Modificar valor False a string vacía en el campo motivo_receptor
  mesures/reobje2.py
  mesures/reobjeagrecl.py
  mesures/reobjecil.py
  mesures/reobjeincl.py
Labels: bug, to be merged :octocat:

#73 Cambio de formato en los ficheros CUPSDAT y CUPS45
  mesures/cupsdat.py
  mesures/dates/date.py
  spec/generation_files_spec.py
Labels: WIP, distri, adaptaciones
